### ISSUE TITLE
Where to put ‘Merging’ operation？

### ISSUE THREAD

**Issue by yuranusduke** [yucornetto/GG-Transformer#1]
Thanks to the excellent paper!
However, I've noticed that in figure 2
![image](https://user-images.githubusercontent.com/77255167/120948119-10632980-c774-11eb-8859-3aa01035398c.png),
merging operation happens after MLP, but in Eq 10. and Eq 11, 
![image](https://user-images.githubusercontent.com/77255167/120948180-3c7eaa80-c774-11eb-9178-114657fd7e39.png),
which is before MLP.
Thanks!

**Comment by yucornetto** [comment]
Thanks for your interest and pointing out the issue!

Actually, it does not matter to put Merging before or after the MLP module, since MLP does not involve any spatial-related operation. The results should be identical.

In our implementation, we put it before MLP. Thanks again and we will update the figure, and we will also clean and organize the code soon.
